### ISSUE TITLE
strange behaviour with reverse_geocode and requirement.txt

### ISSUE THREAD

**Issue by aliva** [thampiman/reverse-geocoder#24]
ok this is really strange for me, this is my `requirements.txt` file

```
numpy
scipy
reverse_geocoder
```

 `pip install -r` throws this error

```
Collecting numpy (from -r a.txt (line 1))
  Using cached numpy-1.11.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting scipy (from -r a.txt (line 2))
  Using cached scipy-0.17.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting reverse_geocoder (from -r a.txt (line 3))
  Using cached reverse_geocoder-1.4.tar.gz
    Complete output from command python setup.py egg_info:
    /tmp/easy_install-0Izs8j/scipy-0.18.0rc2/setup.py:322: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      warnings.warn("Unrecognized setuptools command, proceeding with "
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-CKf1DC/reverse-geocoder/setup.py", line 26, in <module>
        long_description=read('README.txt')
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "~/.virtualenvs/tmp-bc4c49e1bc2ee018/local/lib/python2.7/site-packages/setuptools/dist.py", line 348, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "~/.virtualenvs/tmp-bc4c49e1bc2ee018/local/lib/python2.7/site-packages/setuptools/dist.py", line 394, in fetch_build_eggs
        replace_conflicting=True,
      File "~/.virtualenvs/tmp-bc4c49e1bc2ee018/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "~/.virtualenvs/tmp-bc4c49e1bc2ee018/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1092, in best_match
        return self.obtain(req, installer)
      File "~/.virtualenvs/tmp-bc4c49e1bc2ee018/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1104, in obtain
        return installer(requirement)
      File "~/.virtualenvs/tmp-bc4c49e1bc2ee018/local/lib/python2.7/site-packages/setuptools/dist.py", line 461, in fetch_build_egg
        return cmd.easy_install(req)
      File "~/.virtualenvs/tmp-bc4c49e1bc2ee018/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 664, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "~/.virtualenvs/tmp-bc4c49e1bc2ee018/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 694, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "~/.virtualenvs/tmp-bc4c49e1bc2ee018/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 875, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "~/.virtualenvs/tmp-bc4c49e1bc2ee018/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1114, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "~/.virtualenvs/tmp-bc4c49e1bc2ee018/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1100, in run_setup
        run_setup(setup_script, args)
      File "~/.virtualenvs/tmp-bc4c49e1bc2ee018/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 249, in run_setup
        raise
      File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "~/.virtualenvs/tmp-bc4c49e1bc2ee018/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 197, in setup_context
        yield
      File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "~/.virtualenvs/tmp-bc4c49e1bc2ee018/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 168, in save_modules
        saved_exc.resume()
      File "~/.virtualenvs/tmp-bc4c49e1bc2ee018/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 143, in resume
        six.reraise(type, exc, self._tb)
      File "~/.virtualenvs/tmp-bc4c49e1bc2ee018/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 156, in save_modules
        yield saved
      File "~/.virtualenvs/tmp-bc4c49e1bc2ee018/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 197, in setup_context
        yield
      File "~/.virtualenvs/tmp-bc4c49e1bc2ee018/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 246, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "~/.virtualenvs/tmp-bc4c49e1bc2ee018/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 276, in run
        return func()
      File "~/.virtualenvs/tmp-bc4c49e1bc2ee018/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 245, in runner
        _execfile(setup_script, ns)
      File "~/.virtualenvs/tmp-bc4c49e1bc2ee018/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-0Izs8j/scipy-0.18.0rc2/setup.py", line 415, in <module>
    
      File "/tmp/easy_install-0Izs8j/scipy-0.18.0rc2/setup.py", line 395, in setup_package
    
    ImportError: No module named numpy.distutils.core
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-CKf1DC/reverse-geocoder/
```

but when I install reverse-geocoder manually it works just fine :-|

```
$ pip install numpy
Collecting numpy
  Using cached numpy-1.11.1-cp27-cp27mu-manylinux1_x86_64.whl
Installing collected packages: numpy
Successfully installed numpy-1.11.1

$ pip install scipy
Collecting scipy
  Using cached scipy-0.17.1-cp27-cp27mu-manylinux1_x86_64.whl
Installing collected packages: scipy
Successfully installed scipy-0.17.1
 
$ pip install reverse_geocoder
Collecting reverse_geocoder
  Using cached reverse_geocoder-1.4.tar.gz
Requirement already satisfied (use --upgrade to upgrade): numpy in ./lib/python2.7/site-packages (from reverse_geocoder)
Requirement already satisfied (use --upgrade to upgrade): scipy in ./lib/python2.7/site-packages (from reverse_geocoder)
Building wheels for collected packages: reverse-geocoder
  Running setup.py bdist_wheel for reverse-geocoder ... done
  Stored in directory: ~/.cache/pip/wheels/c8/57/b0/2fdff550c3ffa9f023792bd891b206e47c6d3b094a7562a122
Successfully built reverse-geocoder
Installing collected packages: reverse-geocoder
Successfully installed reverse-geocoder-1.4
```

extra info:

```
Python 2.7.11+
pip 8.1.2
ubuntu 16.04

Python 2.7.6
pip 8.1.2
ubuntu 14.04
```

**Comment by thampiman** [comment]
This was a strange bug. Fixed now in v1.5.
