### ISSUE TITLE
Exception if eventlet is used

### ISSUE THREAD

**Issue by tito** [thampiman/reverse-geocoder#55]
If eventlet is used (like if you do something with flask_socketio), the library display lot of Exception during the loading of geocoded file:

```python
>>> import eventlet
>>> eventlet.monkey_patch()
>>> import reverse_geocoder as rg
>>> coordinates = (51.5214588,-0.1729636),(9.936033, 76.259952),(37.38605,-122.08385)
>>> results = rg.search(coordinates) # default mode = 2
Loading formatted geocoded file...
Exception ignored in: <function _after_fork at 0x7f57a9dfba60>
Traceback (most recent call last):
  File "/home/tito/.conda/envs/cozyconnect/lib/python3.7/threading.py", line 1343, in _after_fork
    assert len(_active) == 1
AssertionError: 
Exception ignored in: <function _after_fork at 0x7f57a9dfba60>
Traceback (most recent call last):
  File "/home/tito/.conda/envs/cozyconnect/lib/python3.7/threading.py", line 1343, in _after_fork
    assert len(_active) == 1
AssertionError: 
Exception ignored in: <function _after_fork at 0x7f57a9dfba60>
...
>>> results
[OrderedDict([('lat', '51.51116'), ('lon', '-0.18426'), ('name', 'Bayswater'), ('admin1', 'England'), ('admin2', 'Greater London'), ('cc', 'GB')]), OrderedDict([('lat', '9.93988'), ('lon', '76.26022'), ('name', 'Cochin'), ('admin1', 'Kerala'), ('admin2', 'Ernakulam'), ('cc', 'IN')]), OrderedDict([('lat', '37.38605'), ('lon', '-122.08385'), ('name', 'Mountain View'), ('admin1', 'California'), ('admin2', 'Santa Clara County'), ('cc', 'US')])]
```

**Comment by Alex-ley** [comment]
Did you try with mode=1? Then there will be no multiprocessing, which I assume is causing the issues here?
