### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by jp-embedded** [thampiman/reverse-geocoder#67]
I sometimes get segfault using the included c++ lib:

0x0000fffff7b7fa08 in PyUnicode_AsUTF8AndSize () from /lib/aarch64-linux-gnu/libpython3.8.so.1.0
(gdb) bt
#0  0x0000fffff7b7fa08 in PyUnicode_AsUTF8AndSize () from /lib/aarch64-linux-gnu/libpython3.8.so.1.0
#1  0x0000aaaaaab0ed8c in ReverseGeocode::search[abi:cxx11](double, double) (this=0xfffffffff1b8, _lat=55.715805000000003, _lon=12.436966) at ReverseGeocode.cpp:73
#2  0x0000aaaaaaaaf540 in main () at tesla_cron.cpp:605
(gdb) 

(gdb) up
#1  0x0000aaaaaab0ed8c in ReverseGeocode::search[abi:cxx11](double, double) (this=0xfffffffff1b8, _lat=55.715805000000003, _lon=12.436966) at ReverseGeocode.cpp:73
73                const char* s1 = PyUnicode_AsUTF8(value);
(gdb) p value
$1 = (PyObject *) 0xffffde03d600
(gdb) p *value
$2 = {ob_refcnt = 281474406537808, ob_type = 0x0}
(gdb)

**Comment by jp-embedded** [comment]
happends when invoked more than once
